### ISSUE TITLE
Freezes during loading rp

### ISSUE THREAD

**Issue by adriaan1313** [HyperCubeMC/connected-block-textures#16]
While loading a specific resource pack with cbt, Minecraft freezes and gets stuck at the loading bar, giving the following error:
```
Error checking resource pack priority
java.io.FileNotFoundException: minecraft:textures/missingno.png
	at net.minecraft.class_3294.method_14486(class_3294.java:67)
	at net.minecraft.class_3304.method_14486(class_3304.java:62)
	at net.minecraft.class_1088.checkPack(class_1088.java:1188)
	at net.minecraft.class_1088.md077dda$lambda$checkCtmConfigs$3$1(class_1088.java:1169)
	at io.github.nuclearfarts.cbt.util.CBTUtil.allMatchThrowable(CBTUtil.java:43)
	at net.minecraft.class_1088.checkCtmConfigs(class_1088.java:1169)
	at net.minecraft.class_1088.md077dda$lambda$injectCbtModels$1$3(class_1088.java:1148)
	at java.base/java.util.HashMap.forEach(HashMap.java:1425)
	at net.minecraft.class_1088.redirect$zoo000$injectCbtModels(class_1088.java:1144)
	at net.minecraft.class_1088.<init>(class_1088.java:217)
	at net.minecraft.class_1092.method_18178(class_1092.java:52)
	at net.minecraft.class_1092.method_18789(class_1092.java:19)
	at net.minecraft.class_4080.method_18791(class_4080.java:11)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
It seems not to cope well with a missing texture. It does not happen without the rp or without the mod, it did work with of.
Might be related to https://github.com/Nuclearfarts/connected-block-textures/issues/26, seeing as it is a 32x32 pack.

Update: I have narrowed it down to three specific files, namely crafting_table_side/crafting_table_front.properties:
```
matchTile=crafting_table_front
faces=sides
method=random
tiles=0-12
```
crafting_table_side/crafting_table_side.properties:
```
matchTile=crafting_table_side
faces=sides
method=random
tiles=0-12
```
cake/cake_top.properties:
```
MatchBlocks=cake
method=random
faces=top
tiles=0-3
```
all files (0-12 for crafting table/0-3 for cake) exist

**Comment by adriaan1313** [comment]
Probably the same issue as https://github.com/HyperCubeMC/connected-block-textures/issues/17
